fix oc logs for SDN, add --all-containers and --prefix options (#1524)
a `kube-rbac-proxy` container was added to the sdn pod,
so the regular `oc logs -l app=sdn` command won't work
anymore, we need to either specify the container or
use `--all-containers=true`

```
STDERR:
error: a container name must be specified for pod sdn-w7bwn, choose one of: [sdn kube-rbac-proxy]
```