OVN: error if no leader
On Single Node OpenShift there is no OVN leader, leader_id is nil.

Instead of

```
NoMethodError: undefined method `[]' for nil:NilClass
```
use the regular error message