networkplugin: workaround api timeout (#1405)
Because we are parsing :response which includes stderr
we are parsing the error message instead of the stdout.

The fact that we have an timeout error with valid output
is not fatal for this step.

```bash
[00:34:22] INFO> Shell Commands: oc get clusternetwork default --template=\{\{.pluginName\}\}

redhat/openshift-ovs-networkpolicy
STDERR:
I0729 20:34:24.148105 1154034 request.go:621] Throttling request took 1.060477114s, request: GET:https://api.rbrattai-s46a24.qe.devcluster.openshift.com:6443/apis/operators.coreos.com/v1?timeout=32s
I0729 20:34:34.148292 1154034 request.go:621] Throttling request took 11.060291252s, request: GET:https://api.rbrattai-s46a24.qe.devcluster.openshift.com:6443/apis/app.triggermesh.io/v1alpha1?timeout=32s
I0729 20:34:44.348259 1154034 request.go:621] Throttling request took 21.259996577s, request: GET:https://api.rbrattai-s46a24.qe.devcluster.openshift.com:6443/apis/tufin.io/v1alpha1?timeout=32s

[00:35:04] INFO> Exit Status: 0

RuntimeError: the env network plugin is s46a24.qe.devcluster.openshift.com:6443/apis/tufin.io/v1alpha1?timeout=32s
 but expecting ["multitenant", "networkpolicy"].
```