wait_till: fix failure case, return false instead of nil
In the `wait_till_*` functions if the timeout has already
expired before the first status check then we set
`res` to `nil` which causes the access `res[:response]`
to raise

```ruby
      undefined method `[]' for nil:NilClass (NoMethodError)
      verification-tests/lib/openshift/resource.rb:351:in `wait_till_ready'
```

This is not the correct error message.

The steps that call `wait_till_ready` have a more detailed error
message that indicates which exact resource failed.

```ruby
  @result = _resource.wait_till_ready(_user, timeout)
  unless @result[:success]
    raise %Q{#{type} "#{_resource.name}" did not become ready within } \
       "#{timeout} seconds"
  end
```

If we set `res = BushSlicer::ResultHash.new(:success => false)` then
`@result[:success]` will fail and we get a good error message

```ruby
RuntimeError: BushSlicer::Pod ovnkube-master-vw8v6 did not become ready within timeout
verification-tests/features/step_definitions/resources.rb:107:in `block (2 levels) in <top (required)>'
```

Also use `wait_for` `stats` to calculate duration